### PR TITLE
Added Steph'ss bio

### LINKED ISSUE #32: Add Steph's volunteer profile

### PR DESCRIPTION
**Pull request by stephwdev**
Resolves #32

### CODE REVIEW

**Review by jillBreau — COMMENTED** [review]
Hi Steph, the addition of your bio looks great! One thing first, I _just_ merged the branch containing Susan's bio into `main`, so could you now merge `main` into your branch? My bad, it would have been easier if I had merged already!

Otherwise - I think that the style changes look good, but they aren't currently consistent with our other files, and I haven't actually had a conversation with @lesleychard about a style guide that we intend to follow yet, so I might rope her in to look at this PR after all!

**Comment by stephwdev** [comment]
@jillBreau I can merge for sure! That's one of the checklist things at work anyways so usually my process, so not sure if we should add something similar here? I know we're probably not making nearly as many changes but something to think about.

Aw, that was my VSCode linter. I didn't even notice! I can certainly change it back.

**Comment by jillBreau** [comment]
@stephwdev Good point, a checklist would be a nice idea, maybe something we could add to the repo's README file (although you're right about less frequent changes I'm sure)! But yes I definitely assumed that was a linter and not manual or anything - changing it back would probably be easiest in the context of this PR but maybe a standard linter would be something else to think about for contributors of the repo in the future!

**Review by jillBreau — APPROVED** [review]
Looks good to me!

**Pull request merged**
